### PR TITLE
Add search

### PR DESCRIPTION
**Pull request by abrookins**
Add search powered by redis-sitesearch.

This PR adds a search form in two places on the Developer site:

1. The home page
2. The sidebar of content pages

## Homepage:

Homepage search

## Sidebar:

Sidebar search

### CODE REVIEW

**Comment by ajeetraina** [comment]
While testing, I do see that the output overlapping with the existing site.
The top right corner will be the right place to put this search button.

Screenshot 2021-03-02 at 1 24 06 PM


Screenshot 2021-03-02 at 1 23 54 PM

**Comment by abrookins** [comment]
It looks like the CSS didn’t load at all. Hmm.

**Comment by abrookins** [comment]
Can you tell me the exact commands you ran to run the server?

**Comment by ajeetraina** [comment]
@abrookins You can follow https://github.com/redis-developer/redis-developer.github.io

Step 1: Clone the repository
Step 2: yarn install
Step 3. yarn build
Step 4. npm run serve
Step 5. Open localhost:3000

**Comment by abrookins** [comment]
Thanks, Ajeet. Asking because (as you can see in the screenshot) the CSS loaded fine in my local dev. So I'll need to track down what is different between our setups. What browser was this?

I'll return to this soon and attempt to place the search box up in the header. However, it does look and work a lot better when the build tooling works and the CSS loads.

**Comment by collabnix** [comment]
Tested it on the Chrome browser. Will try it out in another browser.

**Comment by ajeetraina** [comment]
@abrookins Is it possible for you to raise a new PR? Clone the latest repo and then try to raise PR.

**Comment by abrookins** [comment]
I'll reapply to latest master.

**Pull request closed without merging**
