### PR TITLE
Update RedisJSON docs for Jedis 4

### PR DESCRIPTION
**Pull request by banker**

### CODE REVIEW

**Review by simonprickett — APPROVED** [review]
@banker looks good to me - I did one small commit to fix a code block that wasn't rendering properly.  I won't merge this in case you don't want to launch this article immediately so will leave that to you.

**Comment by banker** [comment]
Thanks, @simonprickett. I'd like to hold off on merging until Jedis 4.0 is released.

**Comment by simonprickett** [comment]
> Thanks, @simonprickett. I'd like to hold off on merging until Jedis 4.0 is released.

Sounds good - I've labeled this "DO NOT MERGE" for now.

**Comment by banker** [comment]
@simonprickett Jedis 4.0 has been released. Can you merge when you get a moment?

**Pull request merged**
